### ISSUE TITLE
1.1.3+

### ISSUE THREAD

**Issue by Wesseldr** [moaxaca/async-redis#12]
From version 1.1.3 on using the module with typescript gives an error:

server.ts(13,29): error TS2306: File ./node_modules/async-redis/index.d.ts' is not a module.

Line 13 reads: 
import * as asyncRedis from 'async-redis';

version 1.1.2 and below works fine.

Hope this helps.

Regards,
        Wessel

**Comment by samstarling** [comment]
I also have this problem with anything after 1.1.2. @Wesseldr: Did you ever find a solution?
