### ISSUE TITLE
Is there any way of setting timeout?

### ISSUE THREAD

**Issue by nicogon** [moaxaca/async-redis#19]
in case await command get stuck there forever

**Comment by moaxaca** [comment]
Currently, we wait for the underlying driver to throw. I am guessing the payload is extremely large or there is some sort of connection issue. I will consider adding a timeout decoration around the library as that would add good utility. 

You probably want to wrap it yourself for now. Something like:
https://repl.it/@moaxaca/JS-Wrap-with-timeout

That example addresses the blocking aspect, but there are some other concerns with leaking memory and possibly threads if your using file io. 

I am going to close this for now as the redis driver should be handling this, but I will consider it for the roadmap.
