### ISSUE TITLE
Connecting to a non-localhost Redis instance

### ISSUE THREAD

**Issue by fishnux** [moaxaca/async-redis#2]
```js
const asyncRedisClient = require("async-redis").createClient(1111, '8.8.8.8');
```
It looks like the second argument ("8.8.8.8") is being ignored:
```
Error: Redis connection to 127.0.0.1:1111 failed - connect ECONNREFUSED 127.0.0.1:1111
```

Edit: Just found this workaround:
```js
const asyncRedisClient = require("async-redis").createClient(`redis://8.8.8.8:1111`);
```

**Comment by moaxaca** [comment]
@fishnux I will work this ASAP ty for notice.

**Comment by moaxaca** [comment]
Fixed with https://github.com/moaxaca/async-redis/commit/8a645340325b58663831f6153f26c301e03575c8 closing issue
