### ISSUE TITLE
node-redlock conflits with async-redis

### ISSUE THREAD

**Issue by AndreLion** [moaxaca/async-redis#20]
[node-redlock](https://github.com/mike-marcacci/node-redlock) is not working with [async-redis](https://www.npmjs.com/package/async-redis), sample code 
```
// ...do something here...
```
will never execute.

[ref](https://github.com/mike-marcacci/node-redlock/issues/53)

**Comment by moaxaca** [comment]
@AndreLion I will look at this weekend. I didn't originally design this library with 100% interoperability with external libraries.

**Comment by moaxaca** [comment]
This is higher effort than anticipated it will take me sometime

**Comment by moaxaca** [comment]
Stale
