### ISSUE TITLE
Typescript type definitions.

### ISSUE THREAD

**Issue by lasersox** [moaxaca/async-redis#22]
It would be nice to have typescript type definitions!

**Comment by moaxaca** [comment]
@lasersox I believe someone is working on this already

**Comment by moaxaca** [comment]
But I agree TS definitions would be great :)

**Comment by jtushman** [comment]
++ on this would love me some types

**Comment by MariaPet** [comment]
When will we have the TS definitions?

**Comment by philipp-sapronov** [comment]
https://www.npmjs.com/package/@types/async-redis

**Comment by moaxaca** [comment]
@philipp-sapronov Wow this is so excellent and humbling. Thank you for writing this up. I will update the readme right now.

**Comment by PAStheLoD** [comment]
Thanks @philipp-sapronov !

This might not be the perfect place to ask this (maybe filing a bug at DefinitelyTyped is?), but probably anyone who already uses the types watches this issue.

So, it seems client.set("k", "v") doesn't work, it complains, that it wants 5-6 arguments, but only 2 are given. I've tried it with TS 3.5, 3.6, 3.7, 3.8, 3.9.

For some reason it seems the shorter overload signatures of set are not accessible, and TS insists it wants the longest.

Has anyone encountered this?
