### ISSUE TITLE
connect-redis conflicts with async-redis

### ISSUE THREAD

**Issue by hnngo** [moaxaca/async-redis#24]
I am using [connect-redis](https://www.npmjs.com/package/connect-redis) as a Redis session store backed by node_redis. Everything is fine if I use a normal redisClient without decorating it by async-redis. However after I decorated redisClient with async-redis, the connect-redis module seem didn't work anymore.

I hope it would be better if decorate function does not change the original redisClient and returning a new object instead

**Comment by moaxaca** [comment]
This has been a feature request for a while. I haven't had a lot of time to look into the library. I am going to close and use this ticket as the tracker. 

https://github.com/moaxaca/async-redis/issues/21
