### ISSUE TITLE
Clean up mocha.opts

### ISSUE THREAD

**Issue by dcstone09** [moaxaca/async-redis#3]
Currently, we have to specify in the package.json the mocha file if we follow convention. Mocha can pick this up on it's own.

https://mochajs.org/#mochaopts

**Comment by moaxaca** [comment]
@dcstone09 Looks good, I will assign this to you. Assuming you don't mind.

**Comment by dcstone09** [comment]
Taken care of in PR #4

**Comment by moaxaca** [comment]
Closing merged with: 8f49aa7ec60596a65105eff104b674be35031071
