### ISSUE TITLE
doesnt work with redis-rejson 

### ISSUE THREAD

**Issue by nelsonlarocca** [moaxaca/async-redis#34]
using this code:

```
const redis = require("redis"),
  rejson = require("redis-rejson"),
  asyncRedis = require("async-redis");

rejson(redis); /* important - this must come BEFORE creating the client */
let redisClient = redis.createClient();
let asyncRedisClient = asyncRedis.decorate(redisClient);
```
retrieving any value is fine, like:

`myString = await asyncRedisClient.get("myKey1");
`

but I always get a boolean true value in myJson if

``myJson = await asyncRedisClient.json_get("myKey2", ".")
``

should it work with redis-rejson ?
thanks

**Comment by moaxaca** [comment]
@nelsonlarocca I've never used redis-rejson I will have to look into their implementation to see what their expecting.  My guess is their using callbacks and async-redis has a backward compatibility bug.
