### ISSUE TITLE
NOAUTH Authentication required (How to handle passwords?)

### ISSUE THREAD

**Issue by dylanh724** [moaxaca/async-redis#43]
My Redis has a password, advised by every quickstart guide:

> ReplyError: Ready check failed: NOAUTH Authentication required.

I pretty much expected this -- but I oddly saw no mention of passwords in the README despite being such a general thing: How to simply include the redis password when connecting?

**Comment by chrisjuchem** [comment]
You can pass the same configuration object that you would provide to the plain redis library. It is documented [here](https://github.com/NodeRedis/node-redis#rediscreateclient).

**Comment by moaxaca** [comment]
Answer from above works
