### ISSUE TITLE
Update redis

### ISSUE THREAD

**Issue by RemiKalbe** [moaxaca/async-redis#45]
Hey 🖖,

Could you update `redis` and `redis-command` to their latest version?
Because right now, this version of redis require `hiredis` which is deal breaking for me.

**Comment by CryogenicPlanet** [comment]
@RemiKalbe A really hacky solution I used is by manually updating the packages with `patch-package` https://www.npmjs.com/package/patch-package

Here is the patch file https://gist.github.com/CryogenicPlanet/098eb730d068633428016c3d0e4250a7

**Comment by luizdesign** [comment]
Another reason to update is the vulnerability in the used redis version.
https://www.npmjs.com/advisories/1662

**Comment by moaxaca** [comment]
Updated in 2.0.0
