### ISSUE TITLE
Connect to localhost even when host/port is given

### ISSUE THREAD

**Issue by jbdev420** [moaxaca/async-redis#7]
When using the async library the createClient method ignores the host and port and connects to localhost

**Comment by moaxaca** [comment]
@jbdev420 I will look into this. For now, you can pass the variables through the URL string. 

const asyncRedisClient = require("async-redis").createClient(`redis://8.8.8.8:1111`);

**Comment by bikov** [comment]
fixed in PR #8

**Comment by moaxaca** [comment]
@bikov @jbdev420 Release with v1.1.4. 

NPM: https://www.npmjs.com/package/async-redis
Github: https://github.com/moaxaca/async-redis/releases/tag/v1.1.4
